#!/bin/bash
#Diyar P, diyar@synlex.se

sudo apt-get install mysql-client

MYSQL_HOST="PUBLIC IP"
MYSQL_PORT="3306"
MYSQL_USER="root"
MYSQL_PASSWORD="password"

# Kontrollera om vi kan nå servern med en port 3306
nc -zv -w 1 "$MYSQL_HOST" "$MYSQL_PORT"


if [ $? -eq 0 ]; then
    echo " MySQL körs"
    
    # Ansluta till mysql
    mysql -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD"
    
 
    
else
    echo "MYSQL KÖRS INTE $MYSQL_HOST:$MYSQL_PORT"
fi
