#!/bin/bash
#diyar@synlex.se

    if ! command -v mysql &> /dev/null; then
        echo " Installera ... om inte finns redan"
        sudo apt-get install mysql-client
    fi
 

function LoggaIn() {
    local host="$1"
    local port="$2"
    local user="$3"
    local password="$4"

  
    nc -zv -w 1 "$host" "$port"

 
    if [ $? -eq 0 ]; then
        echo " MYSQL Anslutas "
 
        mysql -h "$host" -P "$port" -u "$user" -p"$password"
 

    else
        echo " MYSQL KÖRS INTE $host:$port"
    fi
}

# Detaljer 
MYSQL_HOST="192.168.1.240"
MYSQL_PORT="3306"
MYSQL_USER="root"
MYSQL_PASSWORD="password"

 
LoggaIn "$MYSQL_HOST" "$MYSQL_PORT" "$MYSQL_USER" "$MYSQL_PASSWORD"
